name: 'Dev Container Build and Run Action'
description: 'Action to simplify using Dev Containers (https://containers.dev) in GitHub workflows'
author: 'devcontainers'
branding:
  color: purple
  icon: box
inputs:
  tags:
    required: true
    description: List of image tags
  labels:
    required: false
    description: List of labels
  platform:
    required: false
    description: Platforms for which the image should be built. If omitted, defaults to the platform of the GitHub Actions Runner
  pushByDigest:
    required: false
    default: false
    description: Whether the action should append the platform to image tags and output image digests for each platform
  subFolder:
    required: false
    description: Specify a child folder (containing a .devcontainer) instead of using the repository root
    default: ""
  configFile:
    required: false
    description: Specify the path to a devcontainer.json file instead of using `./.devcontainer/devcontainer.json` or `./.devcontainer.json`
    default: ""
  checkoutPath:
    required: false
    description: Specify path to checked out folder if not using default (or for testing with nektos/act)
    default: .
  push:
    required: false
    default: false
    description: Control if images are pushed
  skipContainerUserIdUpdate:
    required: false
    default: "false"
    description: For non-root Dev Containers (i.e. where `remoteUser` is specified), the action attempts to make the container user UID and GID match those of the host user. Set this to true to skip this step (defaults to false)
  userDataFolder:
    required: false
    description: Some steps for building the dev container (e.g. container-features) require generating additional build files. To aid docker build cache re-use, you can use this property to set the path that these files will be generated under and use the actions/cache action to cache that folder across runs
  cacheFrom:
    required: false
    description: Specify additional images to use for build caching
  noCache:
    required: false
    default: "false"
    description: Builds the image with `--no-cache` (takes precedence over `cacheFrom`)
  cacheTo:
    required: false
    description: Specify the image to cache the built image to
outputs:
  imageDigests:
    description: The SHA256 digests of the built images
runs:
  using: 'node20'
  main: 'github-action/run-main.js'
